### ISSUE TITLE
Generator stops working out of nowhere - Warning CS8785

### ISSUE THREAD

**Issue by earloc** [earloc/TypealizR#166]
Occasionally, the generator(s) stop working, which only can be solved by restarting the IDE / Editor of choice. F.e.:

> Warning CS8785 Generator 'TypealizedClassSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'OperationCanceledException' with message 'The operation was canceled.'

> Warning CS8785 Generator 'StringLocalizerExtensionsSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'OperationCanceledException' with message 'The operation was canceled.

Looks like the whole SourceGenerator-SDK is not expecting `OperationCanceledException`, which currently are thrown when "CancellationRequested" by the infrastructure - so avoid that and instead return gracefully.

**Comment by earloc** [comment]
StackTrace for `StringLocalizerExtensionsSourceGenerator`

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.GetValue(LoadTextOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.TextDocumentState.GetTextSynchronously(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AdditionalTextWithState.GetText(CancellationToken cancellationToken)
   at TypealizR.Core.RessourceFile.<>c__DisplayClass22_0.<From>b__7(<>f__AnonymousType4`2 _)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at TypealizR.Core.ResxFileSourceGeneratorBase.<Initialize>b__0_3(SourceProductionContext ctxt, ValueTuple`2 source)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)
```

**Comment by earloc** [comment]
StackTrace for `` 

```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.CodeAnalysis.Host.WeaklyCachedRecoverableValueSource`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.RecoverableTextAndVersion.GetValue(LoadTextOptions options, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.TextDocumentState.GetTextSynchronously(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AdditionalTextWithState.GetText(CancellationToken cancellationToken)
   at TypealizR.Core.RessourceFile.<>c__DisplayClass22_0.<From>b__7(<>f__AnonymousType4`2 _)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at TypealizR.Core.ResxFileSourceGeneratorBase.<Initialize>b__0_3(SourceProductionContext ctxt, ValueTuple`2 source)
   at Microsoft.CodeAnalysis.UserFunctionExtensions.<>c__DisplayClass3_0`2.<WrapUserAction>b__0(TInput1 input1, TInput2 input2, CancellationToken token)

```

**Comment by earloc** [comment]
current solution is not to pass down `cancellationToken` to `AddtionalText.GetText()` and instead fall back to `string.Empty()`, when cancellation is requested by the host.

This hopefully keeps the SourceGenerator alive.
